package io.github.jangalinski.kata.everybodyCodes._2024

private val potionsPerFoe = mapOf(
  'A' to 0,
  'B' to 1,
  'C' to 3,
  'D' to 5,
)

fun quest01p1(input: String) {
  val input =
    "BAACACBCBBBCAAABBBBACBBBBBCCAABBBBCBBCCBCBBBACAACAAABCCCABCCAABBABACBBBBACACBCABBBBCBCCAAABACCBCCBBCBABCAACAAABCBBABBABBAAACBBACBABBBACCBCAAAAACBCBCBACCCBCCACCBAABAABAACBAAABBABBCABAACACABAACBCAABAABBCACCBCBBCAABBACCBAAABBCCAACACACACBBCCCABBAACBCCBBACBBABACCBACBBACCCBBCACBBAAABCBBBCAAAACACCCCCCAAACBBCBBBCBCCAAACAAAACABACBAABABBBCBCACBCABACBBBCACCCBAAABABCAACCBCCBBAACAABCCACCCABAAAAACAABBACBAACCCBAABCACACCAACACACCCAAABCCCCBAAABACAACCAABCCCCABBABBACBCAABBAAAABABABAAACCCCCACABBCAACABBCAAAACBBBACACBAABCCBCCABBCCACACAABBCBAACBABCBCCCBCCBCAAAABBABBCCABCAACACCBCBBCCCABABBCCBCCABBCAAACABBACACAABACBBCABCBAABACABACABACABBCBACBBCCCACAAABCACAAAACCCBBABCBCAACAACBCACAAACBBAAAABCCBAABBBBBAACCCBCBACBCBBCBABBCBABCBBACACCBCBCCBCAAAAABCCABCACCBAAACCBAABCCABBAACCACCBCABBBBCCBCABBBCABCACCCBBBBCABCCCAABCCBCCACACCAABACAABACABBAAAABABCACCCCAACBBABCACBCBBCCCBCAACBCBCCBCBCCBAAAACABABABABABAABACBBBAABCCABBCABBACBBACCCAACACCACAACABABBBABBBCACACCBBCCACCABAAABACACCACACCBBACACCBACBABBBCACBBCBACBCBCCBABCBBBBBBBAACCAB"

  println(input.map {
    when (it) {
      'B' -> 1
      'C' -> 3
      else -> 0
    }
  }.sum())
}

fun quest01p2(input: String = "AxBCDDCAxD"): Int {
  return input.windowed(2, 2).map { it[0] to it[1] }
    .map { potionsPerFoe[it.first] to potionsPerFoe[it.second] }
    .map { it.toList().filterNotNull() }
    .sumOf {
      when (it.size) {
        0 -> 0
        1 -> it.sum()
        else -> it.sum() + 2
      }
    }
}

// In total, you must order: 1 + 6 + 15 + 8 + 0 = 30 potions.
fun quest01p3(input: String = "xBxAAABCDxCCxxx") : Int = input.windowed(3, 3)
  .map { it.map(potionsPerFoe::get).filterNotNull() }
  .map { it.size to it.sum() }
  .map { it.first * (it.first - 1) to it.second }
  .sumOf { it.first + it.second }
